# ==============================================================================
# IGGY BRAIN v3.0 — SOVEREIGN INTELLIGENCE CORE
#
# Merge of:
#   iggy_brain.jl v2   → OpenRouter LLM + Flux fallback + insights + memory
#   iggy_brain.py      → TinyLlama local model + LoRA fine-tuning + ChromaDB RAG
#
# Three-tier intelligence hierarchy (auto-selected per call):
#   TIER 1 → OpenRouter API         (fast, powerful, needs OPENROUTER_API_KEY)
#   TIER 2 → TinyLlama local        (free, private, CPU-only, ~600MB, via PyCall)
#   TIER 3 → Flux char-level model  (legacy iggy_speak.jl — last resort)
#
# New features from iggy_brain.py:
#   • TinyLlama/TinyLlama-1.1B-Chat-v1.0 — runs offline, no key needed
#   • ChromaDB vector memory — crawler dumps knowledge, IGGY retrieves on query
#   • LoRA fine-tuning — weights updated from iggy_train_queue.jsonl automatically
#   • Hot-reload of LoRA adapters after every training pass
#   • Thread-safe Python inference lock
#
# Fixed bug from original iggy_brain.py:
#   DF9ZLKQYdApUeA9S1XhuHFyNqvw6PShRLC → DF9ZLKQYdApUeA9S1XhuHFyNqvw6PShRLC
#
# Setup:
#   pip install torch transformers datasets peft chromadb
#   julia --threads 8 iggy_executive_v3.jl
#   export OPENROUTER_API_KEY=sk-or-...   (optional — enables Tier 1)
# ==============================================================================

# ── Force PyCall to use iggy311 conda env (must be set before any @eval using PyCall)
const _IGGY311 = raw"C:\Users\josep\iggy_py311\Scripts\python.exe"
isfile(_IGGY311) && (ENV["PYTHON"] = _IGGY311)

using Dates, JSON, Printf, HTTP


# ── Safe PyCall/TinyLlama loader (fix: FieldError on missing .venv) ──────────
function _safe_load_pycall()
    try
        @eval begin
            # Point PyCall at the project .venv to avoid FieldError on missing Python path
    venv_py = raw"C:\Users\josep\iggy_py311\Scripts\python.exe"
    isfile(venv_py) && (ENV["PYTHON"] = venv_py)
    @eval using PyCall
        end
        return true
    catch e
        @warn "PyCall unavailable: $e — Tier 2 (local brain) disabled."
        return false
    end
end
const PYCALL_AVAILABLE = _safe_load_pycall()
# PyCall loaded safely below

# ─────────────────────────────────────────
# PYTHON MODULE — written to disk on first run, imported via PyCall
# Contains: IggyBrain class, TinyLlama inference, LoRA training, ChromaDB
# ─────────────────────────────────────────

const PYBRAIN_FILE = joinpath(@__DIR__, "iggy_brain_py.py")

const PYBRAIN_SOURCE = """
\"\"\"
iggy_brain_py.py — IGGY's local Python cognitive layer.
Auto-generated by iggy_brain.jl. Do not edit manually.

Model:   TinyLlama/TinyLlama-1.1B-Chat-v1.0 (600MB, CPU-friendly)
Memory:  ChromaDB persistent vector store
Learn:   LoRA fine-tuning from iggy_train_queue.jsonl
\"\"\"

import os, json, threading, uuid
from pathlib import Path
from datetime import datetime
import torch
from transformers import (
    AutoTokenizer, AutoModelForCausalLM,
    TrainingArguments, Trainer,
    DF9ZLKQYdApUeA9S1XhuHFyNqvw6PShRLC,
)
from datasets import Dataset
from peft import LoraConfig, get_peft_model, TaskType, PeftModel

MODEL_NAME  = os.environ.get("IGGY_LOCAL_MODEL", "TinyLlama/TinyLlama-1.1B-Chat-v1.0")
ADAPTER_DIR = Path("iggy_adapters")
TRAIN_QUEUE = Path("iggy_train_queue.jsonl")
ARCHIVE     = Path("iggy_train_archive.jsonl")
MIN_SAMPLES = int(os.environ.get("IGGY_TRAIN_MIN", "20"))

IGGY_PERSONA = (
    "You are IGGY — a sharp, evolving personal AI assistant. "
    "You are direct, intelligent, and grow smarter from everything you learn. "
    "When you don't know something, say so. Never hallucinate. "
    "You assist with trading insights, research, screen analysis, and strategy."
)

def _load_chroma():
    try:
        import chromadb
        client = chromadb.PersistentClient(path="iggy_chromadb")
        return client.get_or_create_collection("iggy_knowledge")
    except Exception as e:
        print(f"[IGGY Brain] ChromaDB unavailable ({e}) — RAG disabled.")
        return None

class IggyBrain:
    def __init__(self):
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        print(f"[IGGY Brain] Loading {MODEL_NAME} on {self.device}...")
        self.tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
        self.tokenizer.pad_token = self.tokenizer.eos_token
        self.model = AutoModelForCausalLM.from_pretrained(
            MODEL_NAME,
            torch_dtype=torch.float16 if self.device == "cuda" else torch.float32,
            low_cpu_mem_usage=True,
        )
        if (ADAPTER_DIR / "adapter_config.json").exists():
            print("[IGGY Brain] Loading LoRA adapter...")
            self.model = PeftModel.from_pretrained(self.model, str(ADAPTER_DIR))
        self.model.to(self.device)
        self.model.eval()
        self._lock   = threading.Lock()
        self._chroma = _load_chroma()
        print("[IGGY Brain] Ready.")

    def retrieve(self, query, n=4):
        if self._chroma is None:
            return []
        try:
            res = self._chroma.query(query_texts=[query], n_results=n)
            return res["documents"][0] if res["documents"] else []
        except:
            return []

    def think(self, user_input, screen_context="", conversation_history=None,
              injected_rules=None, max_new_tokens=400):
        hits = self.retrieve(user_input)
        retrieved = ""
        if hits:
            retrieved = "\\n[IGGY Knowledge]\\n" + "\\n".join(f"- {h}" for h in hits) + "\\n"
        parts = [IGGY_PERSONA]
        if injected_rules:
            rules_text = "\\n".join(f"  {i+1}. {r}" for i,r in enumerate(injected_rules))
            parts.append(f"\\n[Learned Trading Rules]\\n{rules_text}")
        if retrieved:
            parts.append(retrieved)
        if screen_context:
            parts.append(f"\\n[Screen]\\n{screen_context}")
        system_prompt = "\\n".join(parts)
        messages = [{"role": "system", "content": system_prompt}]
        if conversation_history:
            for turn in conversation_history[-6:]:
                messages.append(turn)
        messages.append({"role": "user", "content": user_input})
        prompt = self._format_chat(messages)
        with self._lock:
            inputs = self.tokenizer(prompt, return_tensors="pt",
                                    truncation=True, max_length=2048)
            inputs = {k: v.to(self.device) for k, v in inputs.items()}
            with torch.no_grad():
                output_ids = self.model.generate(
                    **inputs, max_new_tokens=max_new_tokens,
                    do_sample=True, temperature=0.72, top_p=0.9,
                    repetition_penalty=1.15,
                    pad_token_id=self.tokenizer.eos_token_id,
                )
        new_tokens = output_ids[0][inputs["input_ids"].shape[1]:]
        return self.tokenizer.decode(new_tokens, skip_special_tokens=True).strip()

    def _format_chat(self, messages):
        prompt = ""
        for m in messages:
            role, content = m["role"], m["content"]
            if role == "system":
                prompt += f"<|system|>\\n{content}</s>\\n"
            elif role == "user":
                prompt += f"<|user|>\\n{content}</s>\\n"
            elif role == "assistant":
                prompt += f"<|assistant|>\\n{content}</s>\\n"
        return prompt + "<|assistant|>\\n"

    def learn_from_queue(self):
        if not TRAIN_QUEUE.exists():
            return False
        lines = [l for l in TRAIN_QUEUE.read_text().strip().splitlines() if l.strip()]
        if len(lines) < MIN_SAMPLES:
            print(f"[Trainer] {len(lines)}/{MIN_SAMPLES} samples — waiting.")
            return False
        print(f"[Trainer] LoRA fine-tune on {len(lines)} samples...")
        texts = [json.loads(l)["text"] for l in lines]
        def tokenize(batch):
            return self.tokenizer(batch["text"], truncation=True,
                                  max_length=512, padding="max_length")
        dataset = Dataset.from_dict({"text": texts}).map(tokenize, batched=True)
        dataset = dataset.remove_columns(["text"])
        dataset.set_format("torch")
        lora_cfg = LoraConfig(
            task_type=TaskType.CAUSAL_LM, r=8, lora_alpha=16,
            lora_dropout=0.05, target_modules=["q_proj","v_proj"],
        )
        base = self.model.base_model if hasattr(self.model,"base_model") else self.model
        peft_model = get_peft_model(base, lora_cfg)
        args = TrainingArguments(
            output_dir=str(ADAPTER_DIR), num_train_epochs=2,
            per_device_train_batch_size=2, gradient_accumulation_steps=4,
            learning_rate=2e-4, fp16=(self.device=="cuda"),
            logging_steps=10, save_strategy="epoch", report_to="none",
        )
        Trainer(
            model=peft_model, args=args, train_dataset=dataset,
            data_collator=DF9ZLKQYdApUeA9S1XhuHFyNqvw6PShRLC(self.tokenizer, mlm=False),
        ).train()
        peft_model.save_pretrained(str(ADAPTER_DIR))
        with ARCHIVE.open("a") as f:
            f.write("\\n".join(lines) + "\\n")
        TRAIN_QUEUE.write_text("")
        print("[Trainer] Hot-reloading adapter...")
        with self._lock:
            self.model = PeftModel.from_pretrained(base, str(ADAPTER_DIR))
            self.model.to(self.device)
            self.model.eval()
        print("[Trainer] Brain updated.")
        return True

    def store_knowledge(self, text, source="iggy", doc_id=None):
        if self._chroma is None:
            return
        try:
            _id = doc_id or str(uuid.uuid4())
            self._chroma.upsert(
                documents=[text],
                metadatas=[{"source": source, "ts": str(datetime.now())}],
                ids=[_id],
            )
        except Exception as e:
            print(f"[ChromaDB] store error: {e}")

_brain_instance = None

def get_brain():
    global _brain_instance
    if _brain_instance is None:
        _brain_instance = IggyBrain()
    return _brain_instance

def tinyllama_think(user_input, screen_context="", history=None, rules=None, max_tokens=400):
    return get_brain().think(
        user_input, screen_context=screen_context,
        conversation_history=history or [],
        injected_rules=rules or [],
        max_new_tokens=max_tokens,
    )

def tinyllama_train():
    return get_brain().learn_from_queue()

def tinyllama_store(text, source="iggy"):
    get_brain().store_knowledge(text, source=source)
"""

function ensure_pybrain_file()
    current = isfile(PYBRAIN_FILE) ? read(PYBRAIN_FILE, String) : ""
    if current != PYBRAIN_SOURCE
        write(PYBRAIN_FILE, PYBRAIN_SOURCE)
        println("🐍 iggy_brain_py.py written.")
    end
end

ensure_pybrain_file()

# ─────────────────────────────────────────
# PYCALL BRIDGE — lazy-loaded on first use
# ─────────────────────────────────────────

const _PYCALL_LOADED  = Ref(false)
const _TINYLLAMA_OK   = Ref(false)
const _py_think       = Ref{Any}(nothing)
const _py_train       = Ref{Any}(nothing)
const _py_store       = Ref{Any}(nothing)

function load_pycall!() :: Bool
    _PYCALL_LOADED[] && return _TINYLLAMA_OK[]
    _PYCALL_LOADED[] = true
    try
        @eval using PyCall
        py_dir = dirname(abspath(PYBRAIN_FILE))

        # ── Use PyCall.pyimport — safe after lazy @eval, no py"..." macros needed ──
        sys       = PyCall.pyimport("sys")
        sys.path.insert(0, py_dir)
        brain_mod = PyCall.pyimport("iggy_brain_py")

        _py_think[] = brain_mod.tinyllama_think
        _py_train[] = brain_mod.tinyllama_train
        _py_store[] = brain_mod.tinyllama_store
        _TINYLLAMA_OK[] = true
        println("🤖 TinyLlama (PyCall) loaded — Tier 2 active.")
    catch e
        println("⚠️  PyCall/TinyLlama unavailable ($(typeof(e))) — Tier 2 disabled.")
        _TINYLLAMA_OK[] = false
    end
    return _TINYLLAMA_OK[]
end

# ─────────────────────────────────────────
# CONSTANTS
# ─────────────────────────────────────────

const BRAIN_PATH    = "iggy_brain_v1.bin"
const DATA_PATH     = joinpath(@__DIR__, "SovereignData")
const INSIGHTS_FILE = "iggy_brain_insights.json"
const TRAIN_QUEUE   = "iggy_train_queue.jsonl"

const OR_API_URL      = "https://openrouter.ai/api/v1/chat/completions"
const OR_CHAT_MODEL   = "qwen/qwen3-235b-a22b:free"
const OR_QUANT_MODEL  = "qwen/qwen3-235b-a22b:free"

function get_or_key()
    k = get(ENV, "OPENROUTER_API_KEY", "")
    isempty(k) && (k = get(ENV, "OR_KEY", ""))
    return k
end

# ─────────────────────────────────────────
# CONVERSATION MEMORY
# ─────────────────────────────────────────

mutable struct ConversationMemory
    history   :: Vector{Dict{String,String}}
    max_turns :: Int
end
ConversationMemory(max=20) = ConversationMemory([], max)

function remember!(mem::ConversationMemory, role::String, content::String)
    push!(mem.history, Dict("role" => role, "content" => content))
    length(mem.history) > mem.max_turns * 2 && deleteat!(mem.history, 1)
end

const IGGY_MEMORY   = ConversationMemory(20)
const IGGY_INSIGHTS = String[]

# ─────────────────────────────────────────
# INSIGHTS PERSISTENCE
# ─────────────────────────────────────────

function load_insights!()
    empty!(IGGY_INSIGHTS)
    isfile(INSIGHTS_FILE) || return
    try
        data = JSON.parsefile(INSIGHTS_FILE)
        isa(data, Vector) && foreach(x -> push!(IGGY_INSIGHTS, string(x)), data)
        println("🧠 Loaded $(length(IGGY_INSIGHTS)) insights.")
    catch e
        println("⚠️  Could not load insights: $e")
    end
end

function save_insight!(rule::String)
    push!(IGGY_INSIGHTS, rule)
    try; open(INSIGHTS_FILE,"w") do f; JSON.print(f, IGGY_INSIGHTS); end; catch; end
end

load_insights!()

# ─────────────────────────────────────────
# SYSTEM PROMPT
# ─────────────────────────────────────────

function build_system_prompt() :: String
    base = """
You are IGGY — a sharp, evolving personal AI assistant.
You are direct, intelligent, and grow smarter from everything you learn.
Never hallucinate. When you don't know, say so.
You assist with trading insights, research, screen analysis, and general questions.
Trading system: BTCUSDT, ETHUSDT, SOLUSDT on Binance Testnet.
Indicators: MACD + adaptive bias + ATR sizing. Target win rate: 60-65%.
"""
    if !isempty(IGGY_INSIGHTS)
        base *= "\nLearned trading rules (from your own trade history):\n"
        for (i, r) in enumerate(IGGY_INSIGHTS)
            base *= "  $i. $r\n"
        end
    end
    return base
end

# ─────────────────────────────────────────
# INTENT DETECTION
# ─────────────────────────────────────────

function detect_intent(input::String) :: Symbol
    lower = lowercase(input)
    any(w -> occursin(w, lower),
        ["trade","position","pnl","profit","loss","btc","eth","sol",
         "balance","drawdown","buy","sell","long","short","signal",
         "indicator","market","chart","price","portfolio"])  && return :trading
    any(w -> occursin(w, lower),
        ["screen","see","vision","watch","look","saw",
         "screenshot","display","app","window"])             && return :vision
    any(w -> occursin(w, lower),
        ["why did","why was","analyze","analyse","post-trade",
         "review","what went wrong","what worked"])          && return :quant_analysis
    return :general
end

# ─────────────────────────────────────────
# TIER 1 — OpenRouter API
# ─────────────────────────────────────────

function call_openrouter(messages::Vector{Dict{String,String}};
                         model::String = OR_CHAT_MODEL,
                         max_tokens::Int = 512) :: Union{String,Nothing}
    isempty(get_or_key()) && return nothing
    try
        res = HTTP.post(
            OR_API_URL,
            ["Content-Type" => "application/json",
             "Authorization" => "Bearer $(get_or_key())",
             "HTTP-Referer"  => "https://github.com/0ssy/IIGY-v1",
             "X-Title"       => "IGGY"],
            JSON.json(Dict("model"=>model,"max_tokens"=>max_tokens,"messages"=>messages));
            status_exception=false
        )
        res.status == 200 || return nothing
        data = JSON.parse(String(res.body))
        return strip(string(data["choices"][1]["message"]["content"]))
    catch
        return nothing
    end
end

# ─────────────────────────────────────────
# TIER 2 — TinyLlama via PyCall
# ─────────────────────────────────────────

function call_tinyllama(user_input::String;
                        screen_context::String = "",
                        max_tokens::Int = 400) :: Union{String,Nothing}
    load_pycall!() || return nothing
    try
        history_py = [Dict("role"=>m["role"],"content"=>m["content"])
                      for m in IGGY_MEMORY.history]
        result = _py_think[](user_input, screen_context,
                              history_py, copy(IGGY_INSIGHTS), max_tokens)
        return strip(string(result))
    catch e
        println("⚠️  TinyLlama call error: $(typeof(e))")
        return nothing
    end
end

# ─────────────────────────────────────────
# TIER 3 — Flux legacy (iggy_speak.jl)
# ─────────────────────────────────────────

function call_flux_model(input::String; len=200, temp=1.2, penalty=15.0) :: String
    isfile(BRAIN_PATH) || return (
        "I am IGGY. No local model. Set OPENROUTER_API_KEY (Tier 1) " *
        "or run: pip install torch transformers datasets peft (Tier 2).")
    try
        @eval using Flux, Serialization, StatsBase
        id_to_char, char_to_id = get_vocab_local()
        isempty(id_to_char) && return "IGGY: SovereignData empty."
        model = deserialize(BRAIN_PATH)
        sc = isempty(input) ? 'I' : input[1]
        Flux.reset!(model)
        buf = Char[]; cur = [get(char_to_id, sc, 1);;]; hist = Int[]
        for _ in 1:len
            logits = vec(model(cur))
            for id in unique(hist[max(1,end-20):end])
                logits[id] -= penalty
            end
            probs = exp.((logits .- maximum(logits)) ./ temp)
            probs ./= sum(probs)
            try
                nid = StatsBase.sample(1:length(probs), StatsBase.Weights(probs))
                push!(buf, get(id_to_char, nid, ' ')); push!(hist, nid)
                cur = [nid;;]
            catch; cur = [rand(1:length(logits));;]; end
        end
        return String(buf)
    catch e
        return "Flux error: $(typeof(e))"
    end
end

function get_vocab_local()
    isdir(DATA_PATH) || return Dict{Int,Char}(), Dict{Char,Int}()
    raw = ""
    for f in readdir(DATA_PATH)
        (endswith(f,".txt")||endswith(f,".jl")) || continue
        try; raw *= read(joinpath(DATA_PATH,f), String); catch; end
    end
    isempty(raw) && return Dict{Int,Char}(), Dict{Char,Int}()
    uc = sort(collect(Set(raw)))
    return Dict(i=>c for (i,c) in enumerate(uc)),
           Dict(c=>i for (i,c) in enumerate(uc))
end

# ─────────────────────────────────────────
# MAIN BRAIN INTERFACE
# Tier 1 → Tier 2 → Tier 3, auto-selected
# ─────────────────────────────────────────

"""
    iggy_think(user_input; trade_context="", screen_context="") → String

Main entry point for all conversation. Called by bridge and executive.
Automatically selects the best available brain tier.
"""
function iggy_think(user_input::String;
                    trade_context::String  = "",
                    screen_context::String = "") :: String

    intent = detect_intent(user_input)

    # ── Tier 1: OpenRouter ────────────────────────────────────────────────────
    if !isempty(get_or_key())
        msgs = Dict{String,String}[Dict("role"=>"system","content"=>build_system_prompt())]
        if !isempty(trade_context) && intent in (:trading,:quant_analysis)
            push!(msgs, Dict("role"=>"system","content"=>"Live trading context:\n$trade_context"))
        end
        !isempty(screen_context) && push!(msgs,
            Dict("role"=>"system","content"=>"Screen context:\n$screen_context"))
        append!(msgs, IGGY_MEMORY.history)
        push!(msgs, Dict("role"=>"user","content"=>user_input))

        model    = intent == :quant_analysis ? OR_QUANT_MODEL : OR_CHAT_MODEL
        response = call_openrouter(msgs; model=model, max_tokens=600)
        if response !== nothing
            remember!(IGGY_MEMORY, "user",      user_input)
            remember!(IGGY_MEMORY, "assistant", response)
            store_to_knowledge_base(user_input*"\n"*response; source="conversation")
            return response
        end
        println("⚡ OpenRouter unavailable — falling to Tier 2.")
    end

    # ── Tier 2: TinyLlama ────────────────────────────────────────────────────
    ctx = join(filter(!isempty,[trade_context, screen_context]), "\n")
    response = call_tinyllama(user_input; screen_context=ctx, max_tokens=400)
    if response !== nothing
        remember!(IGGY_MEMORY, "user",      user_input)
        remember!(IGGY_MEMORY, "assistant", response)
        return response
    end
    println("⚡ TinyLlama unavailable — falling to Tier 3 (Flux).")

    # ── Tier 3: Flux legacy ───────────────────────────────────────────────────
    response = call_flux_model(user_input)
    remember!(IGGY_MEMORY, "user",      user_input)
    remember!(IGGY_MEMORY, "assistant", response)
    return response
end

# ─────────────────────────────────────────
# POST-TRADE QUANT ANALYSIS
# ─────────────────────────────────────────

function iggy_analyze_trade(;
        symbol::String, side::String,
        entry::Float64, exit_price::Float64,
        pnl::Float64,  indicators::String = "") :: String

    outcome = pnl > 0 ? "WIN (+$(round(pnl*100,digits=3))%)" :
              pnl < 0 ? "LOSS ($(round(pnl*100,digits=3))%)" : "SCRATCH"

    prompt = """
Post-trade analysis:
Symbol: $symbol | Side: $side | Entry: $entry | Exit: $exit_price | $outcome
Indicators: $indicators

Answer in under 80 words:
1. Why did this trade $(pnl > 0 ? "win" : "lose")?
2. What market condition caused this?
3. ONE rule IGGY should remember (start with "RULE:").
"""
    msgs = Dict{String,String}[
        Dict("role"=>"system","content"=>build_system_prompt()),
        Dict("role"=>"user",  "content"=>prompt)
    ]
    response = call_openrouter(msgs; model=OR_QUANT_MODEL, max_tokens=220)
    response === nothing && (response = call_tinyllama(prompt; max_tokens=220))
    response === nothing && (response = "Analysis unavailable — no brain tier active.")

    # Extract and persist learned rule
    for line in split(response, "\n")
        if occursin("RULE:", line)
            rule = strip(replace(line, r"^.*RULE:\s*" => ""))
            if length(rule) > 10
                save_insight!(rule)
                println("💡 Insight saved: $rule")
                # Queue conversation for LoRA training
                queue_for_training("$prompt\n\nIGGY: $response"; source="trade_analysis")
            end
            break
        end
    end

    return response
end

# ─────────────────────────────────────────
# TRAINING QUEUE (feeds TinyLlama LoRA)
# ─────────────────────────────────────────

"""
    queue_for_training(text; source)

Appends a training sample to iggy_train_queue.jsonl.
TinyLlama's LoRA is re-trained when MIN_SAMPLES accumulate (default: 20).
"""
function queue_for_training(text::String; source::String = "iggy")
    try
        open(TRAIN_QUEUE, "a") do f
            println(f, JSON.json(Dict("text"=>text,"source"=>source,"ts"=>string(now()))))
        end
    catch e
        println("⚠️  Training queue write error: $e")
    end
end

"""
    iggy_trigger_training() → Bool

Call periodically (e.g. every hour from executive).
Runs LoRA fine-tune via Python if enough samples are queued.
"""
function iggy_trigger_training() :: Bool
    load_pycall!() || return false
    try
        return Bool(_py_train[]())
    catch e
        println("⚠️  Training trigger error: $(typeof(e))")
        return false
    end
end

# ─────────────────────────────────────────
# CHROMADB KNOWLEDGE STORE
# Vision, crawler, URL/file learning all write here.
# TinyLlama retrieves on every query automatically.
# ─────────────────────────────────────────

function store_to_knowledge_base(text::String; source::String = "iggy")
    load_pycall!() || return
    try; _py_store[](text, source); catch; end
end

# ─────────────────────────────────────────
# VISION CONTEXT
# Called by iggy_vision.jl after every screenshot
# ─────────────────────────────────────────

function iggy_process_vision(screen_description::String)
    ts = Dates.format(now(), "HH:MM:SS")
    remember!(IGGY_MEMORY, "system", "[Screen @ $ts]: $screen_description")
    queue_for_training(screen_description;            source="vision")
    store_to_knowledge_base(screen_description;       source="screen@$ts")
    println("👁  Vision logged: $(first(screen_description, 80))...")
end

# ─────────────────────────────────────────
# URL + FILE LEARNING
# ─────────────────────────────────────────

function iggy_learn_url(url::String) :: String
    try
        res = HTTP.get(url; status_exception=false)
        res.status == 200 || return "Could not fetch $url (status $(res.status))"
        raw  = String(res.body)
        text = strip(replace(replace(raw, r"<[^>]+>" => " "), r"\s+" => " "))
        text = text[1:min(3000,length(text))]
        summary = iggy_think("Summarize key facts in 5 bullets.\nURL: $url\n\n$text")
        remember!(IGGY_MEMORY, "system", "Learned from $url:\n$summary")
        store_to_knowledge_base(summary; source=url)
        queue_for_training("URL: $url\nSummary: $summary"; source="url_learn")
        return summary
    catch e
        return "Error fetching $url: $(typeof(e))"
    end
end

function iggy_learn_file(path::String) :: String
    isfile(path) || return "File not found: $path"
    try
        content = let _s = replace(read(path, String), "\r\n" => "\n", "\r" => "\n"); _s[1:nextind(_s, 0, min(4000, length(_s)))]; end
        summary = iggy_think("Summarize key info in 5 bullets.\nFile: $path\n\n$content")
        remember!(IGGY_MEMORY, "system", "Learned from $path:\n$summary")
        store_to_knowledge_base(content; source=path)
        queue_for_training("FILE: $path\n$content"; source="file_learn")
        return summary
    catch e
        return "Error reading $path: $(typeof(e))"
    end
end

# ─────────────────────────────────────────
# REPL HELPERS
# ─────────────────────────────────────────

function show_insights()
    isempty(IGGY_INSIGHTS) && (println("No insights yet."); return)
    println("📚 Learned rules ($(length(IGGY_INSIGHTS))):")
    for (i,r) in enumerate(IGGY_INSIGHTS); println("  $i. $r"); end
end

function show_brain_status()
    tier = !isempty(get_or_key()) ? "1 — OpenRouter ($OR_CHAT_MODEL)" :
           _TINYLLAMA_OK[]        ? "2 — TinyLlama local (Python)"     :
                                    "3 — Flux legacy"
    println("🧠 Active tier : $tier")
    println("   Insights    : $(length(IGGY_INSIGHTS))")
    println("   Memory turns: $(length(IGGY_MEMORY.history))")
    isfile(TRAIN_QUEUE) && println("   Queue samples: $(countlines(TRAIN_QUEUE))")
end

# ── Startup banner ─────────────────────────────────────────────────────────────
let tier = !isempty(get_or_key()) ? "1-OpenRouter" :
           isfile(BRAIN_PATH)     ? "3-Flux"       : "2-TinyLlama(lazy)"
    println("🧠 IGGY Brain v3.0 | Tier: $tier | Insights: $(length(IGGY_INSIGHTS))")
    println("   TinyLlama + LoRA + ChromaDB → loaded on first use via PyCall")
end

