"""
iggy_brain_py.py — IGGY's local Python cognitive layer.
Auto-generated by iggy_brain.jl. Do not edit manually.

Model:   TinyLlama/TinyLlama-1.1B-Chat-v1.0 (600MB, CPU-friendly)
Memory:  ChromaDB persistent vector store
Learn:   LoRA fine-tuning from iggy_train_queue.jsonl
"""

import os, json, threading, uuid
from pathlib import Path
from datetime import datetime
import torch
from transformers import (
     AutoModelForCausalLM,
    TrainingArguments, Trainer,
    DataCollatorForLanguageModeling 
)
from datasets import Dataset
from peft import LoraConfig, get_peft_model, TaskType, PeftModel

MODEL_NAME  = os.environ.get("IGGY_LOCAL_MODEL", "TinyLlama/TinyLlama-1.1B-Chat-v1.0")
ADAPTER_DIR = Path("iggy_adapters")
TRAIN_QUEUE = Path("iggy_train_queue.jsonl")
ARCHIVE     = Path("iggy_train_archive.jsonl")
MIN_SAMPLES = int(os.environ.get("IGGY_TRAIN_MIN", "20"))

IGGY_PERSONA = (
    "You are IGGY — a sharp, evolving personal AI assistant. "
    "You are direct, intelligent, and grow smarter from everything you learn. "
    "When you don't know something, say so. Never hallucinate. "
    "You assist with trading insights, research, screen analysis, and strategy."
)

def _load_chroma():
    try:
        import chromadb
        client = chromadb.PersistentClient(path="iggy_chromadb")
        return client.get_or_create_collection("iggy_knowledge")
    except Exception as e:
        print(f"[IGGY Brain] ChromaDB unavailable ({e}) — RAG disabled.")
        return None

class IggyBrain:
    def __init__(self):
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        print(f"[IGGY Brain] Loading {MODEL_NAME} on {self.device}...")
        self.tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
        self.tokenizer.pad_token = self.tokenizer.eos_token
        self.model = AutoModelForCausalLM.from_pretrained(
            MODEL_NAME,
            torch_dtype=torch.float16 if self.device == "cuda" else torch.float32,
            low_cpu_mem_usage=True,
        )
        if (ADAPTER_DIR / "adapter_config.json").exists():
            print("[IGGY Brain] Loading LoRA adapter...")
            self.model = PeftModel.from_pretrained(self.model, str(ADAPTER_DIR))
        self.model.to(self.device)
        self.model.eval()
        self._lock   = threading.Lock()
        self._chroma = _load_chroma()
        print("[IGGY Brain] Ready.")

    def retrieve(self, query, n=4):
        if self._chroma is None:
            return []
        try:
            res = self._chroma.query(query_texts=[query], n_results=n)
            return res["documents"][0] if res["documents"] else []
        except:
            return []

    def think(self, user_input, screen_context="", conversation_history=None,
              injected_rules=None, max_new_tokens=400):
        hits = self.retrieve(user_input)
        retrieved = ""
        if hits:
            retrieved = "\n[IGGY Knowledge]\n" + "\n".join(f"- {h}" for h in hits) + "\n"
        parts = [IGGY_PERSONA]
        if injected_rules:
            rules_text = "\n".join(f"  {i+1}. {r}" for i,r in enumerate(injected_rules))
            parts.append(f"\n[Learned Trading Rules]\n{rules_text}")
        if retrieved:
            parts.append(retrieved)
        if screen_context:
            parts.append(f"\n[Screen]\n{screen_context}")
        system_prompt = "\n".join(parts)
        messages = [{"role": "system", "content": system_prompt}]
        if conversation_history:
            for turn in conversation_history[-6:]:
                messages.append(turn)
        messages.append({"role": "user", "content": user_input})
        prompt = self._format_chat(messages)
        with self._lock:
            inputs = self.tokenizer(prompt, return_tensors="pt",
                                    truncation=True, max_length=2048)
            inputs = {k: v.to(self.device) for k, v in inputs.items()}
            with torch.no_grad():
                output_ids = self.model.generate(
                    **inputs, max_new_tokens=max_new_tokens,
                    do_sample=True, temperature=0.72, top_p=0.9,
                    repetition_penalty=1.15,
                    pad_token_id=self.tokenizer.eos_token_id,
                )
        new_tokens = output_ids[0][inputs["input_ids"].shape[1]:]
        return self.tokenizer.decode(new_tokens, skip_special_tokens=True).strip()

    def _format_chat(self, messages):
        prompt = ""
        for m in messages:
            role, content = m["role"], m["content"]
            if role == "system":
                prompt += f"<|system|>\n{content}</s>\n"
            elif role == "user":
                prompt += f"<|user|>\n{content}</s>\n"
            elif role == "assistant":
                prompt += f"<|assistant|>\n{content}</s>\n"
        return prompt + "<|assistant|>\n"

    def learn_from_queue(self):
        if not TRAIN_QUEUE.exists():
            return False
        lines = [l for l in TRAIN_QUEUE.read_text().strip().splitlines() if l.strip()]
        if len(lines) < MIN_SAMPLES:
            print(f"[Trainer] {len(lines)}/{MIN_SAMPLES} samples — waiting.")
            return False
        print(f"[Trainer] LoRA fine-tune on {len(lines)} samples...")
        texts = [json.loads(l)["text"] for l in lines]
        def tokenize(batch):
            return self.tokenizer(batch["text"], truncation=True,
                                  max_length=512, padding="max_length")
        dataset = Dataset.from_dict({"text": texts}).map(tokenize, batched=True)
        dataset = dataset.remove_columns(["text"])
        dataset.set_format("torch")
        lora_cfg = LoraConfig(
            task_type=TaskType.CAUSAL_LM, r=8, lora_alpha=16,
            lora_dropout=0.05, target_modules=["q_proj","v_proj"],
        )
        base = self.model.base_model if hasattr(self.model,"base_model") else self.model
        peft_model = get_peft_model(base, lora_cfg)
        args = TrainingArguments(
            output_dir=str(ADAPTER_DIR), num_train_epochs=2,
            per_device_train_batch_size=2, gradient_accumulation_steps=4,
            learning_rate=2e-4, fp16=(self.device=="cuda"),
            logging_steps=10, save_strategy="epoch", report_to="none",
        )
        Trainer(
            model=peft_model, args=args, train_dataset=dataset,
            data_collator=DataCollatorForLanguageModeling(self.tokenizer, mlm=False),
        ).train()
        peft_model.save_pretrained(str(ADAPTER_DIR))
        with ARCHIVE.open("a") as f:
            f.write("\n".join(lines) + "\n")
        TRAIN_QUEUE.write_text("")
        print("[Trainer] Hot-reloading adapter...")
        with self._lock:
            self.model = PeftModel.from_pretrained(base, str(ADAPTER_DIR))
            self.model.to(self.device)
            self.model.eval()
        print("[Trainer] Brain updated.")
        return True

    def store_knowledge(self, text, source="iggy", doc_id=None):
        if self._chroma is None:
            return
        try:
            _id = doc_id or str(uuid.uuid4())
            self._chroma.upsert(
                documents=[text],
                metadatas=[{"source": source, "ts": str(datetime.now())}],
                ids=[_id],
            )
        except Exception as e:
            print(f"[ChromaDB] store error: {e}")

_brain_instance = None

def get_brain():
    global _brain_instance
    if _brain_instance is None:
        _brain_instance = IggyBrain()
    return _brain_instance

def tinyllama_think(user_input, screen_context="", history=None, rules=None, max_tokens=400):
    return get_brain().think(
        user_input, screen_context=screen_context,
        conversation_history=history or [],
        injected_rules=rules or [],
        max_new_tokens=max_tokens,
    )

def tinyllama_train():
    return get_brain().learn_from_queue()

def tinyllama_store(text, source="iggy"):
    get_brain().store_knowledge(text, source=source)
